name: msml
channels:
  - defaults
dependencies:
  - python=3.12.7
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - pip
  - pip:
      - mlflow==2.19.0
      - fastapi
      - uvicorn
      - prometheus-client
      - pydantic
